### ISSUE TITLE
V4 Auth not working

### ISSUE THREAD

**Issue by vedit** [bloomreach/s4cmd#34]
V4 Auth requiring regions such as eu-central-1 is not working with the following error

```
[Thread Failure] S3ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InvalidRequest</Code><Message>The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.</Message><RequestId>02FA63493DA8A72F</RequestId><HostId>XANdyiE6GccqIuN9bgHmY8wXcY8ge65pzC/OWnXRxmpsU9oAmX9xfjF4A+57Kw0ue5DMgMHyIGU=</HostId></Error>
```

**Comment by tliebig** [comment]
I second that. I don't speak Python, making me unable to fix the error myself.

From what I see, this should be quite straightforward. Here's Amazons docs about the signature algorithm:
http://docs.aws.amazon.com/AmazonS3/latest/API/sig-v4-authenticating-requests.html

**Comment by bkw** [comment]
+1

**Comment by peterkuiper** [comment]
FWIW, I don't speak Python either but I cobbled up a solution for anyone having the same problem:

https://github.com/peterkuiper/s4cmd/tree/sigv4-working

I added 3 parameters:

--sigv4
--endpoint-url
--region

At least it works for my use-case :) It was the most elegant solution I was able to come up with (I was in a hurry). For more information about the problem you can also checkout this blog:

http://philipp.adelt.net/5/posts/2015/02/list-all-s3-files/

**Comment by chouhanyang** [comment]
Now that s4cmd 2.0 switch to boto3. Can someone let me know if this is still a problem? 

Thanks.

**Comment by peterkuiper** [comment]
Seems to have been fixed now, thanks :)

**Comment by perjahn** [comment]
No, s4cmd 2.0.1 + S3 in Frankfurt still doesn't work, the same issue/error.

**Comment by lrkwz** [comment]
Same from italy

    region = eu-central-1

could not find then way to specify ```region```.
I've reverted to the basic aws-cli interface :(

**Comment by vaneek** [comment]
The V4 signature issue can be solved by setting the following in your ~/.aws/config file,

```
[default]
        region = eu-central-1
        s3 = 
          use_accelerate_endpoint = true
          signature_version = s3v4
```

The will force the signature to V4. Other options can be found [here](http://docs.aws.amazon.com/cli/latest/topic/s3-config.html)

**Comment by pako-pl** [comment]
You could also set an environment variable:

```
export AWS_DEFAULT_REGION=eu-central-1
```

But using the `~/.aws/config` file seems to be the best solution to the problem.

**Comment by navinpai** [comment]
Since this issue is resolved, going ahead and closing this github issue. Thanks @pako-pl  and @vaneek for chipping in!
