### ISSUE TITLE
pytz not required and s4cmd shell script not executable on all systems

### ISSUE THREAD

**Issue by teran-mckinney** [bloomreach/s4cmd#62]
Hi,

It looks like pytz is a missing requirement. I have a couple systems that don't have it installed and it seems that s4cmd doesn't list it as an explicit requirement.

Also, I haven't tracked down why, but in Circle Enterprise with pip 8.1.2, the s4cmd shell script is installed non-executable, so you can't just do `pip install s4cmd; s4cmd ls`. Not sure if anyone else will see that or not. I haven't been able to reproduce on my local system in a virtualenv.

Thanks for a handy utility. We can easily work around these, but I figured I should bring this up.

-Teran

**Comment by chouhanyang** [comment]
Thanks for noticing this. Will update setup.py.

**Comment by chouhanyang** [comment]
Fixed, and also updated pypi repo.

**Comment by mvherweg** [comment]
I actually encountered this exact issue yesterday as well on Ubuntu 12.04 with s4cmd 2.0.1
Also tried with a forced 2.0.0 version, same thing.
So seems like the issue is still around.

**Comment by teran-mckinney** [comment]
@mvherweg I've been forcing 1.5.20 (or similar?) or emulating `s4cmd` (`python -m s4cmd $*`, or something like that).

This was also on Precise in a Circle container, so that lines up. Thanks for posting about that.
